In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sb

In [2]:
car = pd.read_csv(r"datasets\quikr_car.csv")

In [3]:
car = car[car['Price'] != ("Ask For Price")]

In [4]:
backup = car.copy()

In [5]:
car = car[car['year'].str.isnumeric()]

In [6]:
car['year'] = car['year'].astype('int')

In [7]:
car = car[car['Price'] != ("Ask For Price")]

In [8]:
car['Price'] = car['Price'].str.replace(",","").astype('int')

In [9]:
car.info()

<class 'pandas.core.frame.DataFrame'>
Index: 819 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        819 non-null    object
 1   company     819 non-null    object
 2   year        819 non-null    int64
 3   Price       819 non-null    int64
 4   kms_driven  819 non-null    object
 5   fuel_type   816 non-null    object
dtypes: int64(2), object(4)
memory usage: 44.8+ KB

In [10]:
car['kms_driven'] = car['kms_driven'].str.split(" ").str.get(0).str.replace(",","")

In [11]:
car = car[car['kms_driven'].str.isnumeric()]

In [12]:
car['kms_driven'].astype('int')

0       45000
1          40
3       28000
4       36000
6       41000
        ...
883     50000
885     30000
886    132000
888     27000
889     40000
Name: kms_driven, Length: 817, dtype: int64

In [13]:
car = car[~car['fuel_type'].isna()]

In [14]:
car['name'].str.split(" ").str.slice(0,3).str.join(' ')

0         Hyundai Santro Xing
1         Mahindra Jeep CL550
3           Hyundai Grand i10
4      Ford EcoSport Titanium
6                   Ford Figo
                ...
883        Maruti Suzuki Ritz
885            Tata Indica V2
886      Toyota Corolla Altis
888              Tata Zest XM
889        Mahindra Quanto C8
Name: name, Length: 816, dtype: object

In [15]:
car = car.reset_index(drop=True)

In [16]:
car.describe()

              year         Price
count   816.000000  8.160000e+02
mean   2012.444853  4.117176e+05
std       4.002992  4.751844e+05
min    1995.000000  3.000000e+04
25%    2010.000000  1.750000e+05
50%    2013.000000  2.999990e+05
75%    2015.000000  4.912500e+05
max    2019.000000  8.500003e+06

In [17]:
car[car['Price']<6e6].reset_index(drop=True)

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,80000,45000,Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,425000,40,Diesel
2,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,325000,28000,Petrol
3,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,575000,36000,Diesel
4,Ford Figo,Ford,2012,175000,41000,Diesel
...,...,...,...,...,...,...
810,Maruti Suzuki Ritz VXI ABS,Maruti,2011,270000,50000,Petrol
811,Tata Indica V2 DLE BS III,Tata,2009,110000,30000,Diesel
812,Toyota Corolla Altis,Toyota,2009,300000,132000,Petrol
813,Tata Zest XM Diesel,Tata,2018,260000,27000,Diesel
814,Mahindra Quanto C8,Mahindra,2013,390000,40000,Diesel