In [66]:
import numpy as np 
import sklearn as sk
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sb

In [67]:
movies = pd.read_csv(r"datasets\tmdb_5000_movies.csv")
credits = pd.read_csv(r"datasets\tmdb_5000_credits.csv")

In [68]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [69]:
movies = movies.merge(credits,left_on="id",right_on="movie_id")

In [70]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,spoken_languages,status,tagline,title_x,vote_average,vote_count,movie_id,title_y,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [71]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title_x', 'vote_average',
       'vote_count', 'movie_id', 'title_y', 'cast', 'crew'],
      dtype='object')

In [72]:
movies = movies[['movie_id','title_x','overview','genres','keywords','cast','crew']]

In [73]:
movies.isnull().sum()

movie_id    0
title_x     0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [74]:
movies.dropna(inplace=True)

In [75]:
movies.isnull().sum()

movie_id    0
title_x     0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [76]:
movies.shape

(4800, 7)

In [77]:
a = movies.iloc[1200].genres

In [78]:
import ast  
def convert(obj):
   L = []
   for i in ast.literal_eval(obj):
      L.append(i['name'])
   return L

In [79]:
ast.literal_eval(a)

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 53, 'name': 'Thriller'}]

In [80]:
movies['genres'] = movies['genres'].apply(convert)

In [81]:
movies.head(3)

,movie_id,title_x,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."

In [82]:
def convert2(obj):
   L = []
   counter = 0
   for i in ast.literal_eval(obj):
      if counter != 3:
         L.append(i['name'])
         counter += 1
      else:
         break   
   return L

In [83]:
movies['keywords'] = movies['keywords'].apply(convert)

In [84]:
movies['cast'] = movies.cast.apply(convert2)

In [85]:
movies.head()

,movie_id,title_x,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [86]:
movies.iloc[0].crew

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [87]:
def fetch_director(obj):
   L = []
   for i in ast.literal_eval(obj):
      if i["job"] == "Director":
         L.append(i['name'])
         break
   return L

In [88]:
movies['crew'] = movies.crew.apply(fetch_director)

In [89]:
movies.head(5)

,movie_id,title_x,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [90]:
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ","")for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ","")for i in x])
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ","")for i in x])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ","")for i in x])

In [91]:
movies.head(1)

,movie_id,title_x,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]

In [92]:
movies['title'] = movies['title_x']

In [93]:
movies['overview'] = movies['overview'].apply(lambda x: x.split())

In [94]:
movies.head(1)

,movie_id,title_x,overview,genres,keywords,cast,crew,title
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],Avatar

In [95]:
movies['tags'] = movies['overview']+ movies['genres']+ movies['keywords']+ movies['cast']+ movies['crew']

In [96]:
movies.head(1)

,movie_id,title_x,overview,genres,keywords,cast,crew,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."

In [97]:
new_df = movies[['movie_id','title','tags']]

In [98]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [99]:
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\avdhoot\AppData\Local\Temp\ipykernel_18112\3089450492.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

In [100]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [101]:
from sklearn.feature_extraction.text import CountVectorizer

In [102]:
s=['Congrats. You have won a lottery and you can get lottery amount by calling the lottery number',
   'Give your bank account details for lottery amount to be credited to your bank account',
   'lottery for sure if the bank account details are verified']

In [103]:
s[0].split()

['Congrats.',
 'You',
 'have',
 'won',
 'a',
 'lottery',
 'and',
 'you',
 'can',
 'get',
 'lottery',
 'amount',
 'by',
 'calling',
 'the',
 'lottery',
 'number']

In [104]:
s[1].split()  # tokenization

['Give',
 'your',
 'bank',
 'account',
 'details',
 'for',
 'lottery',
 'amount',
 'to',
 'be',
 'credited',
 'to',
 'your',
 'bank',
 'account']

In [105]:
vect = CountVectorizer(stop_words='english')
op =  vect.fit_transform(s).toarray()
op

array([[0, 0, 1, 1, 0, 0, 3, 1, 0, 0, 1],
       [2, 2, 0, 0, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0]])

In [106]:
pd.DataFrame(op,columns=vect.get_feature_names_out(),index=['s[1]','s[2]','s[3]'])

,account,bank,calling,congrats,credited,details,lottery,number,sure,verified,won
s[1],0,0,1,1,0,0,3,1,0,0,1
s[2],2,2,0,0,1,1,1,0,0,0,0
s[3],1,1,0,0,0,1,1,0,1,1,0

In [107]:
# stop words

In [108]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(stop_words= 'english',max_features= 5000)

In [109]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [110]:
vectors.shape

(4800, 5000)

In [111]:
cv.get_feature_names_out()[0:200]

array(['000', '007', '10', '100', '11', '12', '13', '14', '15', '16',
       '17', '17th', '18', '18th', '19', '1930s', '1940s', '1950s',
       '1960s', '1970s', '1980', '1980s', '1985', '1990s', '19th',
       '19thcentury', '20', '200', '2003', '2009', '20th', '21st', '23',
       '24', '25', '30', '300', '3d', '40', '50', '500', '60', '60s',
       '70', '70s', 'aaron', 'aaroneckhart', 'abandoned', 'abducted',
       'abigailbreslin', 'abilities', 'ability', 'able', 'aboard',
       'abuse', 'abusive', 'academy', 'accept', 'accepted', 'accepts',
       'access', 'accident', 'accidental', 'accidentally', 'accompanied',
       'accomplish', 'account', 'accountant', 'accused', 'ace', 'achieve',
       'act', 'acting', 'action', 'actionhero', 'actions', 'activist',
       'activities', 'activity', 'actor', 'actors', 'actress', 'acts',
       'actual', 'actually', 'adam', 'adams', 'adamsandler',
       'adamshankman', 'adaptation', 'adapted', 'addict', 'addicted',
       'addiction', 'adolescence', 'adopt', 'adopted', 'adoption',
       'adopts', 'adrienbrody', 'adult', 'adultery', 'adulthood',
       'adults', 'advantage', 'adventure', 'adventures', 'advertising',
       'advice', 'affair', 'affairs', 'affection', 'affections',
       'afghanistan', 'africa', 'african', 'africanamerican',
       'aftercreditsstinger', 'afterlife', 'aftermath', 'age', 'aged',
       'agedifference', 'agency', 'agenda', 'agent', 'agents',
       'aggressive', 'aging', 'ago', 'agree', 'agrees', 'ahead', 'aid',
       'aided', 'aids', 'ailing', 'air', 'airplane', 'airplanecrash',
       'airport', 'aka', 'al', 'alabama', 'alan', 'alaska', 'albert',
       'alcatraz', 'alcohol', 'alcoholic', 'alcoholism', 'alecbaldwin',
       'alex', 'alexkendrick', 'alfredhitchcock', 'alfredmolina', 'ali',
       'alice', 'alien', 'alieninvasion', 'alienlife', 'alienplanet',
       'aliens', 'alike', 'alive', 'allen', 'alliance', 'allied',
       'allies', 'allow', 'allows', 'ally', 'alongside', 'alpacino',
       'alter', 'alternate', 'alternative', 'alzheimer', 'amanda',
       'amandapeet', 'amandaseyfried', 'amateur', 'amazing', 'ambassador',
       'ambition', 'ambitious', 'ambulance', 'ambush', 'america',
       'american', 'americanabroad', 'americanfootball', 'americans',
       'amid', 'amidst', 'amnesia', 'amp', 'amsterdam', 'amusementpark',
       'amy'], dtype=object)

In [112]:
# steaming process    ----->  Stemming is the process of reducing a word to its root form

In [113]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [114]:
ps.stem('mathematics')

'mathemat'

In [115]:
def streming(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [116]:
streming('fuck fucking fucked')

'fuck fuck fuck'

In [117]:
new_df['tags'] = new_df['tags'].apply(streming)

C:\Users\avdhoot\AppData\Local\Temp\ipykernel_18112\206014347.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(streming)

In [118]:
cv.get_feature_names_out(new_df['tags'])

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      shape=(5000,), dtype=object)

In [119]:
cv.get_feature_names_out()[0:200]

array(['000', '007', '10', '100', '11', '12', '13', '14', '15', '16',
       '17', '17th', '18', '18th', '19', '1930s', '1940s', '1950s',
       '1960s', '1970s', '1980', '1980s', '1985', '1990s', '19th',
       '19thcentury', '20', '200', '2003', '2009', '20th', '21st', '23',
       '24', '25', '30', '300', '3d', '40', '50', '500', '60', '60s',
       '70', '70s', 'aaron', 'aaroneckhart', 'abandoned', 'abducted',
       'abigailbreslin', 'abilities', 'ability', 'able', 'aboard',
       'abuse', 'abusive', 'academy', 'accept', 'accepted', 'accepts',
       'access', 'accident', 'accidental', 'accidentally', 'accompanied',
       'accomplish', 'account', 'accountant', 'accused', 'ace', 'achieve',
       'act', 'acting', 'action', 'actionhero', 'actions', 'activist',
       'activities', 'activity', 'actor', 'actors', 'actress', 'acts',
       'actual', 'actually', 'adam', 'adams', 'adamsandler',
       'adamshankman', 'adaptation', 'adapted', 'addict', 'addicted',
       'addiction', 'adolescence', 'adopt', 'adopted', 'adoption',
       'adopts', 'adrienbrody', 'adult', 'adultery', 'adulthood',
       'adults', 'advantage', 'adventure', 'adventures', 'advertising',
       'advice', 'affair', 'affairs', 'affection', 'affections',
       'afghanistan', 'africa', 'african', 'africanamerican',
       'aftercreditsstinger', 'afterlife', 'aftermath', 'age', 'aged',
       'agedifference', 'agency', 'agenda', 'agent', 'agents',
       'aggressive', 'aging', 'ago', 'agree', 'agrees', 'ahead', 'aid',
       'aided', 'aids', 'ailing', 'air', 'airplane', 'airplanecrash',
       'airport', 'aka', 'al', 'alabama', 'alan', 'alaska', 'albert',
       'alcatraz', 'alcohol', 'alcoholic', 'alcoholism', 'alecbaldwin',
       'alex', 'alexkendrick', 'alfredhitchcock', 'alfredmolina', 'ali',
       'alice', 'alien', 'alieninvasion', 'alienlife', 'alienplanet',
       'aliens', 'alike', 'alive', 'allen', 'alliance', 'allied',
       'allies', 'allow', 'allows', 'ally', 'alongside', 'alpacino',
       'alter', 'alternate', 'alternative', 'alzheimer', 'amanda',
       'amandapeet', 'amandaseyfried', 'amateur', 'amazing', 'ambassador',
       'ambition', 'ambitious', 'ambulance', 'ambush', 'america',
       'american', 'americanabroad', 'americanfootball', 'americans',
       'amid', 'amidst', 'amnesia', 'amp', 'amsterdam', 'amusementpark',
       'amy'], dtype=object)

In [130]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [131]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4800, 5000))

In [128]:
from sklearn.metrics.pairwise import cosine_similarity

In [133]:
similarity = cosine_similarity(vectors)

In [134]:
similarity

array([[1.        , 0.08458258, 0.08718573, ..., 0.04559608, 0.        ,
        0.        ],
       [0.08458258, 1.        , 0.06063391, ..., 0.02378257, 0.        ,
        0.02615329],
       [0.08718573, 0.06063391, 1.        , ..., 0.02451452, 0.        ,
        0.        ],
       ...,
       [0.04559608, 0.02378257, 0.02451452, ..., 1.        , 0.03962144,
        0.04229549],
       [0.        , 0.        , 0.        , ..., 0.03962144, 1.        ,
        0.08714204],
       [0.        , 0.02615329, 0.        , ..., 0.04229549, 0.08714204,
        1.        ]], shape=(4800, 4800))

In [135]:
list(enumerate(similarity[0]))

[(0, np.float64(0.9999999999999998)),
 (1, np.float64(0.08458258116519013)),
 (2, np.float64(0.08718572905786445)),
 (3, np.float64(0.074458079104994)),
 (4, np.float64(0.19184045508446734)),
 (5, np.float64(0.1098436937909367)),
 (6, np.float64(0.04078236951430929)),
 (7, np.float64(0.1487044791289829)),
 (8, np.float64(0.06003002251876642)),
 (9, np.float64(0.09802861627917438)),
 (10, np.float64(0.10397504898200727)),
 (11, np.float64(0.09592022754223367)),
 (12, np.float64(0.09158437663089952)),
 (13, np.float64(0.04559607525875532)),
 (14, np.float64(0.12996881122750908)),
 (15, np.float64(0.06367145399670132)),
 (16, np.float64(0.08000711205939975)),
 (17, np.float64(0.14273829330008253)),
 (18, np.float64(0.09620723036050562)),
 (19, np.float64(0.08419653359482289)),
 (20, np.float64(0.05881716976750462)),
 (21, np.float64(0.11277677488692017)),
 (22, np.float64(0.06711560552140244)),
 (23, np.float64(0.0885807893036239)),
 (24, np.float64(0.05405405405405406)),
 (25, np.float64(0.05170108966939356)),
 (26, np.float64(0.1559625734730109)),
 (27, np.float64(0.195976600339204)),
 (28, np.float64(0.11810771907149853)),
 (29, np.float64(0.06590621627456203)),
 (30, np.float64(0.06774581282657174)),
 (31, np.float64(0.16120647005479025)),
 (32, np.float64(0.0863465783552691)),
 (33, np.float64(0.09863939238321438)),
 (34, np.float64(0.0)),
 (35, np.float64(0.10067340828210367)),
 (36, np.float64(0.17348855898381338)),
 (37, np.float64(0.08000711205939975)),
 (38, np.float64(0.08219949365267865)),
 (39, np.float64(0.08336550215650926)),
 (40, np.float64(0.07798128673650545)),
 (41, np.float64(0.1678603981989089)),
 (42, np.float64(0.0)),
 (43, np.float64(0.09208185110322616)),
 (44, np.float64(0.03427955850955305)),
 (45, np.float64(0.08351476906593233)),
 (46, np.float64(0.14097096860865022)),
 (47, np.float64(0.199363055707225)),
 (48, np.float64(0.08561170049453902)),
 (49, np.float64(0.06003002251876642)),
 (50, np.float64(0.1144727614064285)),
 (51, np.float64(0.08094446585163528)),
 (52, np.float64(0.1487044791289829)),
 (53, np.float64(0.04355035563093422)),
 (54, np.float64(0.03163859985841663)),
 (55, np.float64(0.07306621658015879)),
 (56, np.float64(0.14019992744655632)),
 (57, np.float64(0.024507154069793594)),
 (58, np.float64(0.06839411288813299)),
 (59, np.float64(0.07352146220938077)),
 (60, np.float64(0.0186145197762485)),
 (61, np.float64(0.23490461932490855)),
 (62, np.float64(0.08489527199560176)),
 (63, np.float64(0.08284930213349333)),
 (64, np.float64(0.03001501125938321)),
 (65, np.float64(0.01979131233319198)),
 (66, np.float64(0.02279803762937766)),
 (67, np.float64(0.16439898730535726)),
 (68, np.float64(0.1221125021745327)),
 (69, np.float64(0.026846242208560973)),
 (70, np.float64(0.07702442489446452)),
 (71, np.float64(0.07435223956449145)),
 (72, np.float64(0.1389425035941821)),
 (73, np.float64(0.03355780276070122)),
 (74, np.float64(0.20518233866439894)),
 (75, np.float64(0.10529962529853128)),
 (76, np.float64(0.07271792483455794)),
 (77, np.float64(0.014588051152682587)),
 (78, np.float64(0.05134961659630968)),
 (79, np.float64(0.06314740019611717)),
 (80, np.float64(0.05114214254947678)),
 (81, np.float64(0.11168711865749101)),
 (82, np.float64(0.07702442489446452)),
 (83, np.float64(0.1823843010350213)),
 (84, np.float64(0.12527215359889848)),
 (85, np.float64(0.11565903932254226)),
 (86, np.float64(0.07194017065667525)),
 (87, np.float64(0.11277677488692017)),
 (88, np.float64(0.09158437663089954)),
 (89, np.float64(0.058352204610730346)),
 (90, np.float64(0.06213697660012)),
 (91, np.float64(0.16916516233038026)),
 (92, np.float64(0.06314740019611717)),
 (93, np.float64(0.07194017065667525)),
 (94, np.float64(0.1898315991504998)),
 (95, np.float64(0.14237369936287486)),
 (96, np.float64(0.07798128673650545)),
 (97, np.float64(0.07045670884515312)),
 (98, np.float64(0.07610194341477616)),
 (99, np.float64(0.02702702702702703)),
 (100, np.float64(0.0685591170191061)),
 (101, np.float64(0.07798128673650545)),
 (102, np.float64(0.12629480039223434)),
 (103, np.float64(0.08094446585163528)),
 (104, np.float64(0.056388387443460086)),
 (105, np.float64(0.10514994558491725)),
 (106, np.float64(0.06314740019611717)),
 (107, np.float64(0.06263607679944924)),
 (108, np.float64(0.14704292441876157)),
 (109, np.float64(0.06575959492214292)),
 (110, np.float64(0.04559607525875532)),
 (111, np.float64(0.1522038868295523)),
 (112, np.float64(0.07798128673650545)),
 (113, np.float64(0.04393747751637468)),
 (114, np.float64(0.04649905549752771)),
 (115, np.float64(0.04433510985214727)),
 (116, np.float64(0.048478616556371965)),
 (117, np.float64(0.06003002251876642)),
 (118, np.float64(0.034094761699651185)),
 (119, np.float64(0.04393747751637468)),
 (120, np.float64(0.0)),
 (121, np.float64(0.11277677488692017)),
 (122, np.float64(0.11810771907149853)),
 (123, np.float64(0.1139901881468883)),
 (124, np.float64(0.06839411288813299)),
 (125, np.float64(0.07948588753990432)),
 (126, np.float64(0.13513513513513514)),
 (127, np.float64(0.14797064923339878)),
 (128, np.float64(0.0)),
 (129, np.float64(0.09394227846020416)),
 (130, np.float64(0.027399831217559546)),
 (131, np.float64(0.106676149412533)),
 (132, np.float64(0.04559607525875532)),
 (133, np.float64(0.028618190351607124)),
 (134, np.float64(0.13151918984428584)),
 (135, np.float64(0.0)),
 (136, np.float64(0.023728949893812478)),
 (137, np.float64(0.030528125543633176)),
 (138, np.float64(0.12996881122750908)),
 (139, np.float64(0.12234710854292788)),
 (140, np.float64(0.04559607525875532)),
 (141, np.float64(0.0885807893036239)),
 (142, np.float64(0.08585457105482137)),
 (143, np.float64(0.08787495503274936)),
 (144, np.float64(0.050734628943184104)),
 (145, np.float64(0.019510570275964215)),
 (146, np.float64(0.01643989873053573)),
 (147, np.float64(0.056388387443460086)),
 (148, np.float64(0.09863939238321438)),
 (149, np.float64(0.15719549837837185)),
 (150, np.float64(0.16646698038757363)),
 (151, np.float64(0.2056773510573183)),
 (152, np.float64(0.08458258116519013)),
 (153, np.float64(0.07974522228289)),
 (154, np.float64(0.06213697660012)),
 (155, np.float64(0.020712325533373332)),
 (156, np.float64(0.06070834938872646)),
 (157, np.float64(0.10067340828210367)),
 (158, np.float64(0.13549162565314346)),
 (159, np.float64(0.0644825880219161)),
 (160, np.float64(0.11869522585912262)),
 (161, np.float64(0.03224129401095805)),
 (162, np.float64(0.03355780276070122)),
 (163, np.float64(0.05134961659630968)),
 (164, np.float64(0.08108108108108109)),
 (165, np.float64(0.04649905549752771)),
 (166, np.float64(0.12683657235796025)),
 (167, np.float64(0.09158437663089954)),
 (168, np.float64(0.17757120130114434)),
 (169, np.float64(0.08948747402853657)),
 (170, np.float64(0.10793322294408637)),
 (171, np.float64(0.02302046277580654)),
 (172, np.float64(0.21524880100025257)),
 (173, np.float64(0.02348556961505104)),
 (174, np.float64(0.07897471897389846)),
 (175, np.float64(0.07194017065667525)),
 (176, np.float64(0.029526929767874632)),
 (177, np.float64(0.0)),
 (178, np.float64(0.024784079854830485)),
 (179, np.float64(0.07352146220938077)),
 (180, np.float64(0.022371868507134143)),
 (181, np.float64(0.04559607525875532)),
 (182, np.float64(0.1186447494690624)),
 (183, np.float64(0.0713262951621492)),
 (184, np.float64(0.17757120130114434)),
 (185, np.float64(0.05134961659630968)),
 (186, np.float64(0.059808916712167495)),
 (187, np.float64(0.1559625734730109)),
 (188, np.float64(0.022371868507134143)),
 (189, np.float64(0.1162476387438193)),
 (190, np.float64(0.08561170049453902)),
 (191, np.float64(0.04956815970966097)),
 (192, np.float64(0.047960113771116836)),
 (193, np.float64(0.07983920607777244)),
 (194, np.float64(0.0)),
 (195, np.float64(0.06003002251876642)),
 (196, np.float64(0.05264981264926564)),
 (197, np.float64(0.037470006725398436)),
 (198, np.float64(0.058123819371909635)),
 (199, np.float64(0.08787495503274936)),
 (200, np.float64(0.11028219331407116)),
 (201, np.float64(0.0)),
 (202, np.float64(0.03163859985841663)),
 (203, np.float64(0.08458258116519013)),
 (204, np.float64(0.050141221056390024)),
 (205, np.float64(0.07543142864047142)),
 (206, np.float64(0.11241002017619531)),
 (207, np.float64(0.07798128673650545)),
 (208, np.float64(0.12427395320024)),
 (209, np.float64(0.0685591170191061)),
 (210, np.float64(0.07610194341477616)),
 (211, np.float64(0.024784079854830485)),
 (212, np.float64(0.06711560552140243)),
 (213, np.float64(0.059808916712167495)),
 (214, np.float64(0.0)),
 (215, np.float64(0.06711560552140243)),
 (216, np.float64(0.06575959492214292)),
 (217, np.float64(0.0863465783552691)),
 (218, np.float64(0.03874921291460643)),
 (219, np.float64(0.09320546490018)),
 (220, np.float64(0.18009006755629928)),
 (221, np.float64(0.047960113771116836)),
 (222, np.float64(0.08094446585163528)),
 (223, np.float64(0.10529962529853128)),
 (224, np.float64(0.061649620239508984)),
 (225, np.float64(0.047457899787624956)),
 (226, np.float64(0.030528125543633176)),
 (227, np.float64(0.08336550215650926)),
 (228, np.float64(0.11185934253567072)),
 (229, np.float64(0.10892898631973956)),
 (230, np.float64(0.0930725988812425)),
 (231, np.float64(0.0)),
 (232, np.float64(0.11277677488692017)),
 (233, np.float64(0.10514994558491725)),
 (234, np.float64(0.08710071126186844)),
 (235, np.float64(0.07702442489446452)),
 (236, np.float64(0.11624763874381927)),
 (237, np.float64(0.06711560552140244)),
 (238, np.float64(0.11241002017619531)),
 (239, np.float64(0.09248165577087425)),
 (240, np.float64(0.047457899787624956)),
 (241, np.float64(0.08000711205939975)),
 (242, np.float64(0.08219949365267865)),
 (243, np.float64(0.09394227846020416)),
 (244, np.float64(0.09320546490018)),
 (245, np.float64(0.08219949365267865)),
 (246, np.float64(0.07696578428840449)),
 (247, np.float64(0.0)),
 (248, np.float64(0.04516387521771449)),
 (249, np.float64(0.14019992744655632)),
 (250, np.float64(0.0)),
 (251, np.float64(0.04244763599780088)),
 (252, np.float64(0.02054987341316966)),
 (253, np.float64(0.06367145399670132)),
 (254, np.float64(0.07045670884515312)),
 (255, np.float64(0.0)),
 (256, np.float64(0.11314714296070713)),
 (257, np.float64(0.05405405405405406)),
 (258, np.float64(0.01793740008335438)),
 (259, np.float64(0.06213697660012)),
 (260, np.float64(0.20668850837512243)),
 (261, np.float64(0.024507154069793594)),
 (262, np.float64(0.10793322294408637)),
 (263, np.float64(0.09863939238321438)),
 (264, np.float64(0.0)),
 (265, np.float64(0.027788500718836418)),
 (266, np.float64(0.10028244211278005)),
 (267, np.float64(0.06575959492214292)),
 (268, np.float64(0.0533380747062665)),
 (269, np.float64(0.03001501125938321)),
 (270, np.float64(0.08948747402853657)),
 (271, np.float64(0.07194017065667525)),
 (272, np.float64(0.028194193721730043)),
 (273, np.float64(0.021402925123634755)),
 (274, np.float64(0.09097816785925636)),
 (275, np.float64(0.1453095484297741)),
 (276, np.float64(0.06327719971683327)),
 (277, np.float64(0.05381220025006314)),
 (278, np.float64(0.1186447494690624)),
 (279, np.float64(0.09394227846020416)),
 (280, np.float64(0.0)),
 (281, np.float64(0.06590621627456203)),
 (282, np.float64(0.04516387521771449)),
 (283, np.float64(0.027788500718836418)),
 (284, np.float64(0.0186145197762485)),
 (285, np.float64(0.01979131233319198)),
 (286, np.float64(0.07916524933276792)),
 (287, np.float64(0.02632490632463282)),
 (288, np.float64(0.027788500718836418)),
 (289, np.float64(0.04649905549752771)),
 (290, np.float64(0.06327719971683327)),
 (291, np.float64(0.050141221056390024)),
 (292, np.float64(0.09004503377814962)),
 (293, np.float64(0.03001501125938321)),
 (294, np.float64(0.1453095484297741)),
 (295, np.float64(0.106676149412533)),
 (296, np.float64(0.03929887459459296)),
 (297, np.float64(0.04474373701426829)),
 (298, np.float64(0.0)),
 (299, np.float64(0.06025359879550432)),
 (300, np.float64(0.17348855898381338)),
 (301, np.float64(0.09491579957524988)),
 (302, np.float64(0.07045670884515312)),
 (303, np.float64(0.028194193721730043)),
 (304, np.float64(0.06667259338283313)),
 (305, np.float64(0.1926263261127128)),
 (306, np.float64(0.08219949365267865)),
 (307, np.float64(0.11022596991336672)),
 (308, np.float64(0.0685591170191061)),
 (309, np.float64(0.06327719971683327)),
 (310, np.float64(0.03106848830006)),
 (311, np.float64(0.1522038868295523)),
 (312, np.float64(0.10146925788636821)),
 (313, np.float64(0.055577001437672836)),
 (314, np.float64(0.0)),
 (315, np.float64(0.08458258116519013)),
 (316, np.float64(0.0)),
 (317, np.float64(0.0)),
 (318, np.float64(0.0)),
 (319, np.float64(0.10067340828210367)),
 (320, np.float64(0.03106848830006)),
 (321, np.float64(0.0)),
 (322, np.float64(0.213352298825066)),
 (323, np.float64(0.03001501125938321)),
 (324, np.float64(0.024507154069793594)),
 (325, np.float64(0.10067340828210367)),
 (326, np.float64(0.05723638070321425)),
 (327, np.float64(0.027788500718836418)),
 (328, np.float64(0.027788500718836418)),
 (329, np.float64(0.08000711205939975)),
 (330, np.float64(0.10146925788636821)),
 (331, np.float64(0.09119215051751065)),
 (332, np.float64(0.10810810810810811)),
 (333, np.float64(0.024784079854830485)),
 (334, np.float64(0.09802861627917438)),
 (335, np.float64(0.04697113923010208)),
 (336, np.float64(0.07009996372327816)),
 (337, np.float64(0.04604092555161308)),
 (338, np.float64(0.0)),
 (339, np.float64(0.04956815970966097)),
 (340, np.float64(0.050141221056390024)),
 (341, np.float64(0.08336550215650926)),
 (342, np.float64(0.1633934794796094)),
 (343, np.float64(0.019510570275964215)),
 (344, np.float64(0.03001501125938321)),
 (345, np.float64(0.023249527748763855)),
 (346, np.float64(0.0)),
 (347, np.float64(0.0)),
 (348, np.float64(0.06213697660012)),
 (349, np.float64(0.07702442489446452)),
 (350, np.float64(0.04956815970966097)),
 (351, np.float64(0.0)),
 (352, np.float64(0.027788500718836418)),
 (353, np.float64(0.041757384532966166)),
 (354, np.float64(0.02196873875818734)),
 (355, np.float64(0.036992662308349696)),
 (356, np.float64(0.09158437663089952)),
 (357, np.float64(0.0)),
 (358, np.float64(0.06105625108726635)),
 (359, np.float64(0.03163859985841663)),
 (360, np.float64(0.02122381799890044)),
 (361, np.float64(0.07610194341477616)),
 (362, np.float64(0.09672388203287416)),
 (363, np.float64(0.10042266465917388)),
 (364, np.float64(0.023728949893812478)),
 (365, np.float64(0.07610194341477616)),
 (366, np.float64(0.05723638070321425)),
 (367, np.float64(0.0)),
 (368, np.float64(0.13151918984428584)),
 (369, np.float64(0.08108108108108109)),
 (370, np.float64(0.05134961659630968)),
 (371, np.float64(0.09695723311274393)),
 (372, np.float64(0.047960113771116836)),
 (373, np.float64(0.1752499093081954)),
 (374, np.float64(0.038482892144202245)),
 (375, np.float64(0.06213697660011999)),
 (376, np.float64(0.047457899787624956)),
 (377, np.float64(0.0)),
 (378, np.float64(0.0)),
 (379, np.float64(0.05141933776432957)),
 (380, np.float64(0.05264981264926564)),
 (381, np.float64(0.08489527199560176)),
 (382, np.float64(0.0)),
 (383, np.float64(0.04393747751637468)),
 (384, np.float64(0.029061909685954818)),
 (385, np.float64(0.0)),
 (386, np.float64(0.022167554926073633)),
 (387, np.float64(0.023980056885558418)),
 (388, np.float64(0.0)),
 (389, np.float64(0.0885807893036239)),
 (390, np.float64(0.02666903735313325)),
 (391, np.float64(0.05733298225836872)),
 (392, np.float64(0.030528125543633176)),
 (393, np.float64(0.0)),
 (394, np.float64(0.025070610528195012)),
 (395, np.float64(0.05264981264926564)),
 (396, np.float64(0.04433510985214727)),
 (397, np.float64(0.05264981264926564)),
 (398, np.float64(0.0)),
 (399, np.float64(0.023980056885558418)),
 (400, np.float64(0.09158437663089952)),
 (401, np.float64(0.03106848830006)),
 (402, np.float64(0.07897471897389846)),
 (403, np.float64(0.08419653359482289)),
 (404, np.float64(0.06213697660012)),
 (405, np.float64(0.056388387443460086)),
 (406, np.float64(0.021049133398705722)),
 (407, np.float64(0.021586644588817275)),
 (408, np.float64(0.03287979746107146)),
 (409, np.float64(0.0)),
 (410, np.float64(0.09913631941932194)),
 (411, np.float64(0.0533380747062665)),
 (412, np.float64(0.09695723311274393)),
 (413, np.float64(0.14309095175803563)),
 (414, np.float64(0.03001501125938321)),
 (415, np.float64(0.05413539955388112)),
 (416, np.float64(0.05134961659630968)),
 (417, np.float64(0.03287979746107146)),
 (418, np.float64(0.03587480016670876)),
 (419, np.float64(0.06974858324629157)),
 (420, np.float64(0.1139901881468883)),
 (421, np.float64(0.02348556961505104)),
 (422, np.float64(0.11810771907149853)),
 (423, np.float64(0.041757384532966166)),
 (424, np.float64(0.037470006725398436)),
 (425, np.float64(0.06475993376645182)),
 (426, np.float64(0.05446449315986979)),
 (427, np.float64(0.02666903735313325)),
 (428, np.float64(0.056573571480353566)),
 (429, np.float64(0.0)),
 (430, np.float64(0.05134961659630968)),
 (431, np.float64(0.024507154069793594)),
 (432, np.float64(0.11510231387903269)),
 (433, np.float64(0.03163859985841663)),
 (434, np.float64(0.0)),
 (435, np.float64(0.03587480016670876)),
 (436, np.float64(0.0)),
 (437, np.float64(0.025993762245501817)),
 (438, np.float64(0.12392039927415242)),
 (439, np.float64(0.02666903735313325)),
 (440, np.float64(0.025070610528195012)),
 (441, np.float64(0.058123819371909635)),
 (442, np.float64(0.04604092555161308)),
 (443, np.float64(0.06475993376645182)),
 (444, np.float64(0.0)),
 (445, np.float64(0.10028244211278005)),
 (446, np.float64(0.02348556961505104)),
 (447, np.float64(0.06532553344640132)),
 (448, np.float64(0.021586644588817275)),
 (449, np.float64(0.11115400287534567)),
 (450, np.float64(0.021586644588817275)),
 (451, np.float64(0.025367314471592052)),
 (452, np.float64(0.03106848830006)),
 (453, np.float64(0.024784079854830485)),
 (454, np.float64(0.11742784807525519)),
 (455, np.float64(0.061649620239508984)),
 (456, np.float64(0.04393747751637468)),
 (457, np.float64(0.08718572905786445)),
 (458, np.float64(0.04393747751637468)),
 (459, np.float64(0.03504998186163908)),
 (460, np.float64(0.024507154069793594)),
 (461, np.float64(0.14309095175803563)),
 (462, np.float64(0.03271662128033808)),
 (463, np.float64(0.03287979746107146)),
 (464, np.float64(0.0)),
 (465, np.float64(0.0)),
 (466, np.float64(0.14704292441876154)),
 (467, np.float64(0.10701462561817378)),
 (468, np.float64(0.028194193721730043)),
 (469, np.float64(0.06025359879550432)),
 (470, np.float64(0.04604092555161308)),
 (471, np.float64(0.06475993376645182)),
 (472, np.float64(0.10810810810810811)),
 (473, np.float64(0.09394227846020416)),
 (474, np.float64(0.0)),
 (475, np.float64(0.04433510985214727)),
 (476, np.float64(0.1371182340382122)),
 (477, np.float64(0.0)),
 (478, np.float64(0.05479966243511909)),
 (479, np.float64(0.0891578689526865)),
 (480, np.float64(0.09913631941932194)),
 (481, np.float64(0.0)),
 (482, np.float64(0.022167554926073633)),
 (483, np.float64(0.12655439943366653)),
 (484, np.float64(0.029526929767874632)),
 (485, np.float64(0.0533380747062665)),
 (486, np.float64(0.08099356774626426)),
 (487, np.float64(0.1289651760438322)),
 (488, np.float64(0.06746792083200746)),
 (489, np.float64(0.0)),
 (490, np.float64(0.14349920066683505)),
 (491, np.float64(0.10042266465917388)),
 (492, np.float64(0.07702442489446452)),
 (493, np.float64(0.03106848830006)),
 (494, np.float64(0.0)),
 (495, np.float64(0.19344776406574832)),
 (496, np.float64(0.0)),
 (497, np.float64(0.0)),
 (498, np.float64(0.0685591170191061)),
 (499, np.float64(0.0)),
 (500, np.float64(0.02632490632463282)),
 (501, np.float64(0.08284930213349333)),
 (502, np.float64(0.13549162565314346)),
 (503, np.float64(0.07610194341477615)),
 (504, np.float64(0.0)),
 (505, np.float64(0.1371182340382122)),
 (506, np.float64(0.03504998186163908)),
 (507, np.float64(0.25903973506580724)),
 (508, np.float64(0.10269923319261937)),
 (509, np.float64(0.022371868507134143)),